#include "Librerias/InitLab/InitLab.h"
#include "Librerias/EqSolver/EqSolver.h"
#include "Librerias/BinToDec/BinToDec.h"
#include "Librerias/InverseArray/InverseArray.h"
#include "Librerias/FindMaxMin/FindMaxMin.h"
#include "Librerias/MatrixSub/MatrixSub.h"
#include "Librerias/SwapElements/SwapElements.h"
#include "Librerias/InverseString/InverseString.h"
#include "Librerias/StringLen/StringLen.h"
#include "Librerias/WordCount/WordCount.h"
#include "Librerias/StringCopy/StringCopy.h"
#include "Librerias/FindInString/FindInString.h"
#include "Librerias/DateDiff/DateDiff.h"

#include "Librerias/ContarVocalesYConsonantes/ContarVocalesYConsonantes.h"
#include "Librerias/CambioDeMayusculasYMinusculas/CambioDeMayusculasYMinusculas.h"
#include "Librerias/SumaDeNumerosComplejos/SumaDeNumerosComplejos.h"
#include "Librerias/ProductoDeNumerosComplejos/ProductoDeNumerosComplejos.h"

#include "SistemaEstudiantes/lista_estudiantes.h"