#include "InitLab/InitLab.h"
#include "EqSolver/EqSolver.h"
#include "BinToDec/BinToDec.h"
#include "InverseArray/InverseArray.h"
#include "FindMaxMin/FindMaxMin.h"
#include "MatrixSub/MatrixSub.h"
#include "SwapElements/SwapElements.h"
#include "InverseString/InverseString.h"
#include "StringLen/StringLen.h"
#include "WordCount/WordCount.h"
#include "StringCopy/StringCopy.h"
#include "FindInString/FindInString.h"
#include "DateDiff/DateDiff.h"

// #include "ContarVocalesYConsonantes/ContarVocalesYConsonantes.h"
// #include "CambioDeMayusculasYMinusculas/CambioDeMayusculasYMinusculas.h"
// #include "SumaDeNumerosComplejos/SumaDeNumerosComplejos.h"
// #include "ProductoDeNumerosComplejos/ProductoDeNumerosComplejos.h"

#include "Estudiantes/lista_estudiantes.h"